name: asymmetryam.com
favicon: null
layout_spectrum: 0.30998
typography_spectrum: 0.6159
title: ASYMMETRY ASSET MANAGEMENT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#954e34'
    - '#3b3b3b'
    - '#8f8f8f'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
