name: asymmetryam.com
favicon: null
layout_spectrum: 0.4906467883847654
typography_spectrum: 0.6068551349453628
title: ASYMMETRY ASSET MANAGEMENT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9614256857894361
  lightness: 0.02366946660913527
  saturation: 0.7238670389633626
  rhythmicContrast: 0.13133360934443772
purpose: []
