name: asymmetryam.com
favicon: null
layout_spectrum: 0.30998
typography_spectrum: 0.6159
title: ASYMMETRY ASSET MANAGEMENT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ceebea'
    - '#1c373a'
    - '#838e8a'
    - '#dda183'
  brandStrength: 0.9614256857894361
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
