typography_spectrum: 0.6159
color:
  brandColors:
    - '#000000'
    - '#ceebea'
    - '#1c373a'
    - '#838e8a'
    - '#dda183'
  brandStrength: 0
  lightness: 0
  saturation: 0.9375
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.30998
analytics:
  google: null
  facebook: null
  twitter: null
name: asymmetryam.com
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Official website
    url: 'http://www.asymmetryam.com'
    type: external
favicon: null
title: ASYMMETRY ASSET MANAGEMENT
purpose: []
